### ISSUE TITLE
Use proper version numbers for WikDict dictionaries

### ISSUE THREAD

**Issue by humenda** [freedict/tools#14]
Currently, a YYYY-mm-dd timestamp is used as a version number, but it should be
YYYY.mm.dd to be in line with other, hand-written dictionaries.

**Comment by karlb** [comment]
I'll change the <editionStmt><edition></edition></editionStmt> to use dots instead of dashes when exporting from WikDict. While I'm at it, I'll update the data, so it'll probably be ready sometime tomorrow.

**Comment by humenda** [comment]
I was wondering whether we should switch to version numbers like YYYY.MM.1. This
would allow us to patch the dictionaries downstream, if required. If we would
need to make a quick bug fix FD release, we would currently end up with
YYYY.MM.DD.patch, which isn't in line with semantic versioning. What do you
think?

**Comment by karlb** [comment]
I like YYYY.MM.DD because it's so simple to use (no reading of last version number) and still not ambiguous (I don't do multiple releases a day, but I have done multiple in one month). If you make a bugfix release, you could add a postfix to the day/patchlevel like 2018-01-01a or just increment the day part (collisions are possible but highly unlikely in that case), if you don't mind losing the mapping to the exact day.

If none if this works well enough, let me know and I'll add some new version handling code to WikDict.

**Comment by humenda** [comment]
I forgot that you can add `+foo` for a version, so you are right, YYYY.MM.DD
makes most sense.
Thanks

**Comment by karlb** [comment]
Fixed in https://bitbucket.org/wikdict/wikdict-gen/commits/2e763aac855e9c1c388dd093718cc15c79d4e972 . Updated TEI files are now available.
